version: "3.3"
services:
    shlink_server:
        image: shlinkio/shlink:stable
        container_name: shlink_server
        ports:
            - "${SHLINK_SERVER_PORT}:8080"
        environment:
            - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
            - IS_HTTPS_ENABLED=${HTTPS_ENABLED}
            - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
            - DB_DRIVER=mysql
            - DB_HOST=shlink_db
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
        depends_on:
            - shlink_db
        restart: always

    shlink_web_client:
        image: shlinkio/shlink-web-client
        container_name: shlink_web_client
        ports:
            - "${SHLINK_WEB_CLIENT_PORT}:80"

    shlink_db:
        container_name: shlink_db
        image: mysql:5.7
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
